export const CITIES = [
  "São Paulo, SP",
  "Rio de Janeiro, RJ",
  "Belo Horizonte, MG",
  "Brasília, DF",
  "Salvador, BA",
  "Fortaleza, CE",
  "Curitiba, PR",
  "Recife, PE",
  "Porto Alegre, RS",
  "Manaus, AM",
  "Belém, PA",
  "Goiânia, GO",
  "Guarulhos, SP",
  "Campinas, SP",
  "São Luís, MA",
  "Maceió, AL",
  "Campo Grande, MS",
  "São Gonçalo, RJ",
  "Teresina, PI",
  "João Pessoa, PB",
  "Natal, RN",
  "Santo André, SP",
  "Osasco, SP",
  "Sorocaba, SP",
  "Uberlândia, MG",
  "Ribeirão Preto, SP",
  "Cuiabá, MT",
  "Aracaju, SE",
  "Feira de Santana, BA",
  "Joinville, SC",
  "Juiz de Fora, MG",
  "Londrina, PR",
  "Niterói, RJ",
  "Florianópolis, SC",
  "Santos, SP",
  "Vila Velha, ES",
  "Serra, ES",
  "Caxias do Sul, RS",
  "Campos dos Goytacazes, RJ",
  "Macapá, AP",
  "Porto Velho, RO",
  "São José dos Campos, SP",
  "Ribeirão das Neves, MG",
  "Mauá, SP",
  "São José do Rio Preto, SP",
  "Mogi das Cruzes, SP",
  "Diadema, SP",
  "Campina Grande, PB",
  "Jundiaí, SP",
  "Olinda, PE",
  "Carapicuíba, SP",
  "Piracicaba, SP",
  "Bauru, SP",
  "Ananindeua, PA",
  "Cariacica, ES",
  "Vitória, ES",
  "Caucaia, CE",
  "São Vicente, SP",
  "Petrolina, PE",
  "Uberaba, MG",
  "Paulista, PE",
  "Taubaté, SP",
  "Limeira, SP",
  "Suzano, SP",
  "Petrópolis, RJ",
  "Palmas, TO",
  "Boa Vista, RR",
  "Rio Branco, AC",
  "Blumenau, SC",
  "Maringá, PR",
  "Ponta Grossa, PR",
  "Cascavel, PR",
  "Foz do Iguaçu, PR",
  "Pelotas, RS",
  "Canoas, RS",
  "Santa Maria, RS",
  "Volta Redonda, RJ",
  "Franca, SP",
  "Guarujá, SP",
  "Praia Grande, SP",
  "São Bernardo do Campo, SP",
  "Contagem, MG",
  "Betim, MG",
  "Montes Claros, MG",
  "Governador Valadares, MG",
  "Ipatinga, MG",
  "Aparecida de Goiânia, GO",
  "Anápolis, GO",
  "Camaçari, BA",
  "Vitória da Conquista, BA",
  "Itabuna, BA",
  "Ilhéus, BA",
  "Juazeiro, BA",
  "Caruaru, PE",
  "Jaboatão dos Guararapes, PE",
  "Nossa Senhora do Socorro, SE",
  "Parnamirim, RN",
  "Mossoró, RN",
  "Maracanaú, CE",
  "Juazeiro do Norte, CE",
  "Sobral, CE",
  "Imperatriz, MA",
  "Parauapebas, PA",
  "Santarém, PA",
  "Marabá, PA",
  "Dourados, MS",
  "Rondonópolis, MT",
  "Várzea Grande, MT",
];
